# Generated by Django 6.0.2 on 2026-05-02 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StegoAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "recipient_role",
                    models.CharField(
                        blank=True,
                        help_text="Intended recipient role (ADMIN / EMPLOYEE).",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stego_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stego_tokens_used",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "STEGOSHIELD Access Token",
                "verbose_name_plural": "STEGOSHIELD Access Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StegoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ENCODE", "Encode"), ("DECODE", "Decode")],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("IMAGE", "Image")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("UNAUTHORIZED", "Unauthorized"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "message_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the original message (for audit without storing plaintext).",
                        max_length=64,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra metadata about the operation.",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stego_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "STEGOSHIELD Log",
                "verbose_name_plural": "STEGOSHIELD Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
