# Generated by Django 6.0.4 on 2026-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegoshield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stegolog',
            name='cover_text',
            field=models.TextField(blank=True, help_text='Encrypted cover text or filename'),
        ),
        migrations.AddField(
            model_name='stegolog',
            name='passkey',
            field=models.CharField(blank=True, help_text='Encrypted passkey', max_length=255),
        ),
        migrations.AddField(
            model_name='stegolog',
            name='secret_message',
            field=models.TextField(blank=True, help_text='Encrypted secret message'),
        ),
    ]
