# Generated by Django 6.0.2 on 2026-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_prompt", models.TextField()),
                ("processed_prompt", models.TextField(blank=True)),
                ("detected_types", models.JSONField(default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow"),
                            ("BLOCK", "Block"),
                            ("TOKENIZE", "Tokenize"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reasons", models.JSONField(default=list)),
                ("ai_response", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TokenMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_label", models.CharField(max_length=20)),
                ("encrypted_value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
