# Generated by Django 6.0.2 on 2026-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firewall", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenmap",
            name="token_label",
            field=models.CharField(max_length=30),
        ),
    ]
