# Generated by Django 6.0.2 on 2026-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firewall", "0003_zero_trust_token_label_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptlog",
            name="risk_level",
            field=models.CharField(default="LOW", max_length=10),
        ),
        migrations.AddField(
            model_name="promptlog",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
    ]
